# Use Python 3.8 slim image from Docker Hub as the base image
FROM python:3.8-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Inform Docker that the container listens on port 5000
EXPOSE 5000

# Install the Python dependencies from requirements.txt
RUN pip install -r requirements.txt

# Command to run the Flask application
CMD ["python", "flask_api.py"]

